### ISSUE TITLE
baconjs-router Example using React and Webpack

### ISSUE THREAD

**Issue by fknussel** [FoxSportsAustralia/baconjs-router#2]
I've just finished putting together this project using baconjs-router along with React and Webpack:

https://github.com/fknussel/baconjs-router-example

Live version is deployed to https://baconjs-router-example-razvcrijaf.now.sh/

Figured I'd leave it here for future reference as the `example.html` file on the source is not using React nor transpiling the library using the Babel loader for Webpack :)

Dazz Edit:
PR Here: #1

**Comment by darrennolan** [comment]
yay thanks!  Will take a peak.

**Comment by darrennolan** [comment]
Merged in https://github.com/FoxSportsAustralia/baconjs-router/pull/1

Best thanks!

**Comment by darrennolan** [comment]
I lied, I merged it in after your additional PR.  But it's there now :D

Yay again! Thanks :D
